### ISSUE TITLE
How to run on a GPU with limited VRAM

### ISSUE THREAD

**Issue by LYK-love** [chandar-lab/Recall2Imagine#6] opened 2024-04-11 06:37 UTC
Hi, @artemZholus, I want to reproduce your results. But currently O only have an A6000 GPU with about 50GB vram,  48 GB RAM, 256 GB storage. When running 
```
python recall2imagine/train.py \
    --configs mmaze --task gym_memory_maze:MemoryMaze-9x9-v0 \
    --wdb_name memory_maze_9x9 \
    --logdir ./logs_memory_maze_9x9
```
I met
```text
Policy devices: gpu:0
Train devices:  gpu:0
2024-04-11 06:36:20.772287: E external/xla/xla/stream_executor/cuda/cuda_dnn.cc:439] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2024-04-11 06:36:20.772379: E external/xla/xla/stream_executor/cuda/cuda_dnn.cc:443] Memory usage: 9217966080 bytes free, 51033931776 bytes total.
Traceback (most recent call last):
  File "recall2imagine/train.py", line 241, in <module>
    main()
  File "recall2imagine/train.py", line 63, in main
    agent = agt.Agent(env.obs_space, env.act_space, step, config)
  File "/home/lyk/Projects/Recall2Imagine/recall2imagine/jaxagent.py", line 20, in __init__
    super().__init__(agent_cls, *args, **kwargs)
  File "/home/lyk/Projects/Recall2Imagine/recall2imagine/jaxagent.py", line 50, in __init__
    self.varibs = self._init_varibs(obs_space, act_space)
  File "/home/lyk/Projects/Recall2Imagine/recall2imagine/jaxagent.py", line 245, in _init_varibs
    state, varibs = self._init_train(varibs, rng, data['is_first'])
  File "/home/lyk/Projects/Recall2Imagine/recall2imagine/ninjax.py", line 199, in wrapper
    created = init(statics, rng, *args, **kw)
  File "/home/lyk/miniconda3/envs/recall2imagine/lib/python3.8/site-packages/jax/_src/traceback_util.py", line 166, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/home/lyk/miniconda3/envs/recall2imagine/lib/python3.8/site-packages/jax/_src/pjit.py", line 250, in cache_miss
    outs, out_flat, out_tree, args_flat, jaxpr = _python_pjit_helper(
  File "/home/lyk/miniconda3/envs/recall2imagine/lib/python3.8/site-packages/jax/_src/pjit.py", line 163, in _python_pjit_helper
    out_flat = pjit_p.bind(*args_flat, **params)
  File "/home/lyk/miniconda3/envs/recall2imagine/lib/python3.8/site-packages/jax/_src/core.py", line 2677, in bind
    return self.bind_with_trace(top_trace, args, params)
  File "/home/lyk/miniconda3/envs/recall2imagine/lib/python3.8/site-packages/jax/_src/core.py", line 383, in bind_with_trace
    out = trace.process_primitive(self, map(trace.full_raise, args), params)
  File "/home/lyk/miniconda3/envs/recall2imagine/lib/python3.8/site-packages/jax/_src/core.py", line 815, in process_primitive
    return primitive.impl(*tracers, **params)
  File "/home/lyk/miniconda3/envs/recall2imagine/lib/python3.8/site-packages/jax/_src/pjit.py", line 1203, in _pjit_call_impl
    return xc._xla.pjit(name, f, call_impl_cache_miss, [], [], donated_argnums,
  File "/home/lyk/miniconda3/envs/recall2imagine/lib/python3.8/site-packages/jax/_src/pjit.py", line 1187, in call_impl_cache_miss
    out_flat, compiled = _pjit_call_impl_python(
  File "/home/lyk/miniconda3/envs/recall2imagine/lib/python3.8/site-packages/jax/_src/pjit.py", line 1120, in _pjit_call_impl_python
    compiled = _pjit_lower(
  File "/home/lyk/miniconda3/envs/recall2imagine/lib/python3.8/site-packages/jax/_src/interpreters/pxla.py", line 2323, in compile
    executable = UnloadedMeshExecutable.from_hlo(
  File "/home/lyk/miniconda3/envs/recall2imagine/lib/python3.8/site-packages/jax/_src/interpreters/pxla.py", line 2645, in from_hlo
    xla_executable, compile_options = _cached_compilation(
  File "/home/lyk/miniconda3/envs/recall2imagine/lib/python3.8/site-packages/jax/_src/interpreters/pxla.py", line 2555, in _cached_compilation
    xla_executable = dispatch.compile_or_get_cached(
  File "/home/lyk/miniconda3/envs/recall2imagine/lib/python3.8/site-packages/jax/_src/dispatch.py", line 497, in compile_or_get_cached
    return backend_compile(backend, computation, compile_options,
  File "/home/lyk/miniconda3/envs/recall2imagine/lib/python3.8/site-packages/jax/_src/profiler.py", line 314, in wrapper
    return func(*args, **kwargs)
  File "/home/lyk/miniconda3/envs/recall2imagine/lib/python3.8/site-packages/jax/_src/dispatch.py", line 465, in backend_compile
    return backend.compile(built_c, compile_options=options)
jax._src.traceback_util.UnfilteredStackTrace: jaxlib.xla_extension.XlaRuntimeError: FAILED_PRECONDITION: DNN library initialization failed. Look at the errors above for more details.

```

I think it is because my vram is too limited. Is there any way to run your code  in this case?

**Comment by artemZholus** [comment] 2024-04-11 22:16
Hi @LYK-love , the issue above is probably due to wrong installation of cudnn and/or jax. 
(because of the following logs:
```
2024-04-11 06:36:20.772287: E external/xla/xla/stream_executor/cuda/cuda_dnn.cc:439] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2024-04-11 06:36:20.772379: E external/xla/xla/stream_executor/cuda/cuda_dnn.cc:443] Memory usage: 9217966080 bytes free, 51033931776 bytes total.
```
)
I recommend you trying to make sure the following code works
```python
import jax
m = jax.numpy.array([1,])
m@m
```
To make sure it works you can try reinstalling cudnn and/or jax. But a much faster and easier way of resolving this issue is to use docker container with the image we built - here is the instruction https://github.com/chandar-lab/Recall2Imagine?tab=readme-ov-file#docker--singularity
but tl;dr, you can just run these three commands (given that you have the properly installed docker with the nvidia driver support)
```sh
docker pull artemzholus/r2i && docker tag artemzholus/r2i r2i
docker run --rm -it --network host -v $(pwd):/code -w /code r2i bash
# after that, run your training
```
I hope that helps. Please let me know if the issue is resolved.

**Comment by LYK-love** [comment] 2024-04-12 23:47
Hi, @artemZholus, currently, I can not run your code with my env (Ubuntu22.04, CUDA 12.4 and cudnn 12). I think it's because you required `"jax[cuda11_local]"` whereas my cuda version is 12.4.

Therefore, I am trying to modify your dependencies so that I can get an OK configuration with `jax[cuda12_pip]` . I'll comment here for further progress.

**Comment by LYK-love** [comment] 2024-04-13 00:36
> Hi @LYK-love , the issue above is probably due to wrong installation of cudnn and/or jax. (because of the following logs:
> 
> ```
> 2024-04-11 06:36:20.772287: E external/xla/xla/stream_executor/cuda/cuda_dnn.cc:439] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
> 2024-04-11 06:36:20.772379: E external/xla/xla/stream_executor/cuda/cuda_dnn.cc:443] Memory usage: 9217966080 bytes free, 51033931776 bytes total.
> ```
> 
> ) I recommend you trying to make sure the following code works
> 
> ```python
> import jax
> m = jax.numpy.array([1,])
> m@m
> ```
> 
> To make sure it works you can try reinstalling cudnn and/or jax. But a much faster and easier way of resolving this issue is to use docker container with the image we built - here is the instruction https://github.com/chandar-lab/Recall2Imagine?tab=readme-ov-file#docker--singularity but tl;dr, you can just run these three commands (given that you have the properly installed docker with the nvidia driver support)
> 
> ```shell
> docker pull artemzholus/r2i && docker tag artemzholus/r2i r2i
> docker run --rm -it --network host -v $(pwd):/code -w /code r2i bash
> # after that, run your training
> ```
> 
> I hope that helps. Please let me know if the issue is resolved.

Yeah it's a cudann and jax incompability error. My system's cuda is 12.4 and I installed the dependencies via
```sh
conda create -n recall2imagine python=3.8
conda activate recall2imagine
cd env && conda env update -f conda_env.yaml
pip install \
    "jax[cuda11_pip]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html \
    dm-haiku \
    flax \
    optax==0.1.5
```

I also tried with `jax[cuda12_pip]`, also failed:
```sh
conda create -n recall2imagine python=3.8
conda activate recall2imagine
cd env && conda env update -f conda_env.yaml
pip install \
    "jax[cuda12_pip]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html \
    dm-haiku \
    flax \
    optax==0.1.5
```

For both cases, the error messages are like:
```
JAX devices (1): [gpu(id=0)]
Policy devices: gpu:0
Train devices:  gpu:0
2024-04-13 00:45:13.072746: E external/xla/xla/stream_executor/cuda/cuda_dnn.cc:439] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2024-04-13 00:45:13.072820: E external/xla/xla/stream_executor/cuda/cuda_dnn.cc:443] Memory usage: 9901506560 bytes free, 51033931776 bytes total.
Traceback (most recent call last):
  File "recall2imagine/train.py", line 241, in <module>
    main()
  File "recall2imagine/train.py", line 63, in main
    agent = agt.Agent(env.obs_space, env.act_space, step, config)
  File "/home/lyk/Projects/Recall2Imagine/recall2imagine/jaxagent.py", line 20, in __init__
    super().__init__(agent_cls, *args, **kwargs)
  File "/home/lyk/Projects/Recall2Imagine/recall2imagine/jaxagent.py", line 50, in __init__
    self.varibs = self._init_varibs(obs_space, act_space)
  File "/home/lyk/Projects/Recall2Imagine/recall2imagine/jaxagent.py", line 245, in _init_varibs
    state, varibs = self._init_train(varibs, rng, data['is_first'])
  File "/home/lyk/Projects/Recall2Imagine/recall2imagine/ninjax.py", line 199, in wrapper
    created = init(statics, rng, *args, **kw)
  File "/home/lyk/miniconda3/envs/recall2imagine/lib/python3.8/site-packages/jax/_src/traceback_util.py", line 166, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/home/lyk/miniconda3/envs/recall2imagine/lib/python3.8/site-packages/jax/_src/pjit.py", line 250, in cache_miss
    outs, out_flat, out_tree, args_flat, jaxpr = _python_pjit_helper(
  File "/home/lyk/miniconda3/envs/recall2imagine/lib/python3.8/site-packages/jax/_src/pjit.py", line 163, in _python_pjit_helper
    out_flat = pjit_p.bind(*args_flat, **params)
  File "/home/lyk/miniconda3/envs/recall2imagine/lib/python3.8/site-packages/jax/_src/core.py", line 2677, in bind
    return self.bind_with_trace(top_trace, args, params)
  File "/home/lyk/miniconda3/envs/recall2imagine/lib/python3.8/site-packages/jax/_src/core.py", line 383, in bind_with_trace
    out = trace.process_primitive(self, map(trace.full_raise, args), params)
  File "/home/lyk/miniconda3/envs/recall2imagine/lib/python3.8/site-packages/jax/_src/core.py", line 815, in process_primitive
    return primitive.impl(*tracers, **params)
  File "/home/lyk/miniconda3/envs/recall2imagine/lib/python3.8/site-packages/jax/_src/pjit.py", line 1203, in _pjit_call_impl
    return xc._xla.pjit(name, f, call_impl_cache_miss, [], [], donated_argnums,
  File "/home/lyk/miniconda3/envs/recall2imagine/lib/python3.8/site-packages/jax/_src/pjit.py", line 1187, in call_impl_cache_miss
    out_flat, compiled = _pjit_call_impl_python(
  File "/home/lyk/miniconda3/envs/recall2imagine/lib/python3.8/site-packages/jax/_src/pjit.py", line 1120, in _pjit_call_impl_python
    compiled = _pjit_lower(
  File "/home/lyk/miniconda3/envs/recall2imagine/lib/python3.8/site-packages/jax/_src/interpreters/pxla.py", line 2323, in compile
    executable = UnloadedMeshExecutable.from_hlo(
  File "/home/lyk/miniconda3/envs/recall2imagine/lib/python3.8/site-packages/jax/_src/interpreters/pxla.py", line 2645, in from_hlo
    xla_executable, compile_options = _cached_compilation(
  File "/home/lyk/miniconda3/envs/recall2imagine/lib/python3.8/site-packages/jax/_src/interpreters/pxla.py", line 2555, in _cached_compilation
    xla_executable = dispatch.compile_or_get_cached(
  File "/home/lyk/miniconda3/envs/recall2imagine/lib/python3.8/site-packages/jax/_src/dispatch.py", line 497, in compile_or_get_cached
    return backend_compile(backend, computation, compile_options,
  File "/home/lyk/miniconda3/envs/recall2imagine/lib/python3.8/site-packages/jax/_src/profiler.py", line 314, in wrapper
    return func(*args, **kwargs)
  File "/home/lyk/miniconda3/envs/recall2imagine/lib/python3.8/site-packages/jax/_src/dispatch.py", line 465, in backend_compile
    return backend.compile(built_c, compile_options=options)
jax._src.traceback_util.UnfilteredStackTrace: jaxlib.xla_extension.XlaRuntimeError: FAILED_PRECONDITION: DNN library initialization failed. Look at the errors above for more details.

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "recall2imagine/train.py", line 241, in <module>
    main()
  File "recall2imagine/train.py", line 63, in main
    agent = agt.Agent(env.obs_space, env.act_space, step, config)
  File "/home/lyk/Projects/Recall2Imagine/recall2imagine/jaxagent.py", line 20, in __init__
    super().__init__(agent_cls, *args, **kwargs)
  File "/home/lyk/Projects/Recall2Imagine/recall2imagine/jaxagent.py", line 50, in __init__
    self.varibs = self._init_varibs(obs_space, act_space)
  File "/home/lyk/Projects/Recall2Imagine/recall2imagine/jaxagent.py", line 245, in _init_varibs
    state, varibs = self._init_train(varibs, rng, data['is_first'])
  File "/home/lyk/Projects/Recall2Imagine/recall2imagine/ninjax.py", line 199, in wrapper
    created = init(statics, rng, *args, **kw)
jaxlib.xla_extension.XlaRuntimeError: FAILED_PRECONDITION: DNN library initialization failed. Look at the errors above for more details.
Gracefully stopping...
```
I think `jax[cuda11_pip]` will carry the coresponding `cudnn ` and `cuda11` even though I only have cuda12. I don't know how to solve this error.

**Comment by artemZholus** [comment] 2024-04-13 18:37
Hi @LYK-love , I think the best way you can do in your case is to just use docker container. Please follow this instruction https://github.com/chandar-lab/Recall2Imagine?tab=readme-ov-file#docker--singularity

**Comment by artemZholus** [comment] 2024-04-13 18:39
If it's not an option for you, I suggest you to create a **new** conda evironment following the instructions in our repo with the only change in `jax[cuda12_pip]`.  Make sure the following python code works 
```python
import jax
m = jax.numpy.array([1,])
m@m
```

**Comment by LYK-love** [comment] 2024-04-13 22:55
@artemZholus Hi. I have tried using different conda envs. 

> If it's not an option for you, I suggest you to create a **new** conda evironment following the instructions in our repo with the only change in `jax[cuda12_pip]`. Make sure the following python code works
> 
> ```python
> import jax
> m = jax.numpy.array([1,])
> m@m
> ```

Have you tried installing `jax[cuda12_pip]` with python=3.8? Looks like it is only compatible with python=3.9.

**Comment by artemZholus** [comment] 2024-04-14 00:52
@LYK-love we did all experiments for our paper inside of docker containers. Our image has python 3.8, cuda 11.8, cudnn 8.6 and jax 0.4.13 (before opening the code I doublechecked that results are reproducible with 0.4.25) . the image we used was precisely this `docker pull artemzholus/r2i`. That's why the best and the most reliable way is to use docker for experiments. Please use the instruction here https://github.com/chandar-lab/Recall2Imagine?tab=readme-ov-file#docker--singularity

**Comment by LYK-love** [comment] 2024-04-14 01:21
@artemZholus I see. I met a lot of troubles when upgrading to Python=3.9 and jax_cuda12. I will just use the container to do the further development (with VS Code container development plugin). Thanks!

**Comment by artemZholus** [comment] 2024-04-14 01:48
I am glad the issue got resolved. I am closing it, please reopen if you have any other issues.

**Closed as completed by artemZholus** 2024-04-14 01:48 UTC
